# Generated by Django 3.1.5 on 2021-02-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criclet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_name', models.CharField(max_length=30)),
                ('Player_role', models.CharField(max_length=30)),
                ('Player_position', models.CharField(max_length=30)),
            ],
        ),
    ]
